version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - memcached
      - database
    depends_on:
      - memcached
      - database
    environment:
      DEBUG: "true"
      DB_USER: "aladhan"
      DB_PASSWORD: "aladhan"
      DB_NAME: "aladhan_locations"
      DB_HOST: "aa-db"
      DB_PORT: "3306"
      MEMCACHED_HOST: "memcached"
      MEMCACHED_PORT: 11211
    ports:
      - "80:8080"
    volumes:
      - .:/var/www
    privileged: true
    container_name: api

  database:
    image: percona:8
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "api"
      MYSQL_PASSWORD: "api"
      MYSQL_DATABASE: "api"
    container_name: database

  couchdb:
    image: couchdb:3.2
    environment:
      COUCHDB_USER: "api"
      COUCHDB_PASSWORD: "api"
    ports:
      - "5984:5984"
    container_name: couchdb

  memcached:
    image: memcached:1.5
    container_name: memcached

